// index
export const UPDATE_SHOP = 'UPDATE_SHOP'
export const UPDATE_SHOPBANNER = 'UPDATE_SHOPBANNER'
export const UPDATE_SHOPCAT = 'UPDATE_SHOPCAT'
export const UPDATE_SHOPFLOOR1 = 'UPDATE_SHOPFLOOR1'
export const UPDATE_SHOPRECG = 'UPDATE_SHOPRECG'
// article
export const UPDATE_ARTICLES = 'UPDATE_ARTICLES'
export const UPDATE_BANNERS = 'UPDATE_BANNERS'
// article detail
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE'
export const UPDATE_RECARTICLES = 'UPDATE_RECARTICLES'
export const UPDATE_RECGOODS = 'UPDATE_RECGOODS'
// cat
export const UPDATE_CATRESULT = 'UPDATE_CATRESULT'
export const UPDATE_CATBANNER = 'UPDATE_CATBANNER'
// loading
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
// comment
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS'
// orders
export const UPDATE_ORDERS = 'UPDATE_ORDERS'
export const CHNAGE_ORDERS = 'CHNAGE_ORDERS'
export const UDPATE_ORDER = 'UDPATE_ORDER' 

export const UPDATE_TIMEOUTCOUPON = 'UPDATE_TIMEOUTCOUPON'
export const UPDATE_UNUSEFULLCOUPON = 'UPDATE_UNUSEFULLCOUPON'
export const UPDATE_USEFULLCOUPON = 'UPDATE_USEFULLCOUPON'

export const UPDATE_MYLIKES = 'UPDATE_MYLIKES'
export const DELETE_MYLIKES = 'DELETE_MYLIKES'

export const GET_ADDRESS = 'GET_ADDRESS'
export const DELETE_ADDRESS = 'DELETE_ADDRESS'
export const EDIT_ADDRESS = 'EDIT_ADDRESS'
export const CHANGE_STATUS = 'CHANGE_STATUS'

export const GET_COMMENTPOST = 'GET_COMMENTPOST'
export const SET_ONECOMMENT = 'SET_ONECOMMENT'

export const SET_SELECTPARAM = 'SET_SELECTPARAM'
export const GET_GOODDETAIL = 'GET_GOODDETAIL'